# Sử dụng image node phiên bản 14 làm base
FROM node:14

# Đặt thư mục làm việc mặc định
WORKDIR /app

# Sao chép toàn bộ mã nguồn của frontend vào image
COPY ./frontend /app/frontend

# Cài đặt dependencies và build production bundle
WORKDIR /app/frontend
RUN npm install
RUN npm run build

# Port mặc định mà React chạy là 3000
EXPOSE 3000

# CMD để chạy dịch vụ web của React khi container được khởi động
CMD ["npm", "start"]